<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatosPruebaSeeder extends Seeder
{
    public function run(): void
    {
        // ── Clientes (tabla persona) ──────────────────────────────────
        DB::table('persona')->insertOrIgnore([
            [
                'ci'          => '7234891',
                'nombre'      => 'Carlos Alberto Romero Vaca',
                'telefono'    => '76234891',
                'direccion'   => 'Av. Cristo Redentor, Barrio Las Palmas, Santa Cruz',
                'nit'         => null,
                'es_cliente'  => 1,
                'es_personal' => 0,
            ],
            [
                'ci'          => '5812374',
                'nombre'      => 'María Alejandra Suárez Peña',
                'telefono'    => '77812374',
                'direccion'   => 'Equipetrol Norte, Calle 3 Oeste, Santa Cruz',
                'nit'         => null,
                'es_cliente'  => 1,
                'es_personal' => 0,
            ],
            [
                'ci'          => '8143650',
                'nombre'      => 'Juan Pablo Gutiérrez Flores',
                'telefono'    => '78143650',
                'direccion'   => 'Av. Banzer km 5, Urb. Los Jardines, Santa Cruz',
                'nit'         => null,
                'es_cliente'  => 1,
                'es_personal' => 0,
            ],
            [
                'ci'          => '6957423',
                'nombre'      => 'Rosa Elena Medina Chávez',
                'telefono'    => '75957423',
                'direccion'   => 'Plan 3000, Calle 12, Mz. 14, Santa Cruz',
                'nit'         => null,
                'es_cliente'  => 1,
                'es_personal' => 0,
            ],
            [
                'ci'          => '9341287',
                'nombre'      => 'Fernando Javier Ortiz Mamani',
                'telefono'    => '79341287',
                'direccion'   => 'Av. Roca y Coronado, Zona Norte, Santa Cruz',
                'nit'         => null,
                'es_cliente'  => 1,
                'es_personal' => 0,
            ],
            [
                'ci'          => '6428913',
                'nombre'      => 'Daniela Vanessa Quiroga Rojas',
                'telefono'    => '76428913',
                'direccion'   => 'Barrio Urubó, Av. Beni km 8, Santa Cruz',
                'nit'         => null,
                'es_cliente'  => 1,
                'es_personal' => 0,
            ],
            [
                'ci'          => '8217465',
                'nombre'      => 'Ricardo Andrés Salazar Vega',
                'telefono'    => '78217465',
                'direccion'   => 'Av. Cañoto, 4to Anillo, Santa Cruz',
                'nit'         => null,
                'es_cliente'  => 1,
                'es_personal' => 0,
            ],
            [
                'ci'          => '5739182',
                'nombre'      => 'Carla Beatriz Justiniano Heredia',
                'telefono'    => '75739182',
                'direccion'   => 'Urb. Las Misiones, Doble Vía la Guardia, Santa Cruz',
                'nit'         => null,
                'es_cliente'  => 1,
                'es_personal' => 0,
            ],
            [
                'ci'          => '7160924',
                'nombre'      => 'Marcelo Iván Aguilar Soliz',
                'telefono'    => '77160924',
                'direccion'   => 'Barrio Sirari, Av. Mutualista, Santa Cruz',
                'nit'         => null,
                'es_cliente'  => 1,
                'es_personal' => 0,
            ],
            [
                'ci'          => '9582607',
                'nombre'      => 'Gabriela Ximena Rivero Méndez',
                'telefono'    => '79582607',
                'direccion'   => 'Av. Pirai, Zona Sur, Santa Cruz',
                'nit'         => null,
                'es_cliente'  => 1,
                'es_personal' => 0,
            ],
            [
                'ci'          => '6045318',
                'nombre'      => 'Hugo Sebastián Vargas Castro',
                'telefono'    => '76045318',
                'direccion'   => 'Av. Alemana, 3er Anillo Interno, Santa Cruz',
                'nit'         => null,
                'es_cliente'  => 1,
                'es_personal' => 0,
            ],
            [
                'ci'          => '8364791',
                'nombre'      => 'Patricia Noemí Áñez Gutiérrez',
                'telefono'    => '78364791',
                'direccion'   => 'Barrio Sevilla, Av. Paraguá, Santa Cruz',
                'nit'         => null,
                'es_cliente'  => 1,
                'es_personal' => 0,
            ],
            [
                'ci'          => '5928473',
                'nombre'      => 'Luis Fernando Camacho Rivas',
                'telefono'    => '75928473',
                'direccion'   => 'Plan 3000, UV 70, Santa Cruz',
                'nit'         => null,
                'es_cliente'  => 1,
                'es_personal' => 0,
            ],
            [
                'ci'          => '7491036',
                'nombre'      => 'Vanessa Carolina Peña Torrico',
                'telefono'    => '77491036',
                'direccion'   => 'Av. Banzer, Zona Norte, Santa Cruz',
                'nit'         => null,
                'es_cliente'  => 1,
                'es_personal' => 0,
            ],
            [
                'ci'          => '6182054',
                'nombre'      => 'Esteban Mauricio Coca Antezana',
                'telefono'    => '76182054',
                'direccion'   => 'Av. Cristo Redentor, 2do Anillo, Santa Cruz',
                'nit'         => null,
                'es_cliente'  => 1,
                'es_personal' => 0,
            ],
        ]);

        // ── Autos (tabla auto) ────────────────────────────────────────
        // Sin FK hacia persona — el vínculo ocurre luego vía proforma.
        DB::table('auto')->insertOrIgnore([
            [
                'placa' => '3847GKT',
                'marca' => 'Toyota',
                'modelo' => 'Hilux',
                'anio'  => 2019,
                'color' => 'Blanco',
                'tipo'  => 'Camioneta',
            ],
            [
                'placa' => '1562MRZ',
                'marca' => 'Suzuki',
                'modelo' => 'Grand Vitara',
                'anio'  => 2015,
                'color' => 'Gris',
                'tipo'  => 'SUV',
            ],
            [
                'placa' => '7091BNF',
                'marca' => 'Nissan',
                'modelo' => 'Frontier',
                'anio'  => 2021,
                'color' => 'Negro',
                'tipo'  => 'Pickup',
            ],
            [
                'placa' => '4430CVL',
                'marca' => 'Mitsubishi',
                'modelo' => 'L200',
                'anio'  => 2017,
                'color' => 'Rojo',
                'tipo'  => 'Furgoneta',
            ],
            [
                'placa' => '8275JPW',
                'marca' => 'Toyota',
                'modelo' => 'RAV4',
                'anio'  => 2023,
                'color' => 'Azul',
                'tipo'  => 'Hatchback',
            ],
            [
                'placa' => '2918DKM',
                'marca' => 'Chevrolet',
                'modelo' => 'Spark',
                'anio'  => 2018,
                'color' => 'Blanco',
                'tipo'  => 'Hatchback',
            ],
            [
                'placa' => '6053FRT',
                'marca' => 'Toyota',
                'modelo' => 'Corolla',
                'anio'  => 2020,
                'color' => 'Plata',
                'tipo'  => 'Sedán',
            ],
            [
                'placa' => '4172LQB',
                'marca' => 'Volkswagen',
                'modelo' => 'Amarok',
                'anio'  => 2022,
                'color' => 'Negro',
                'tipo'  => 'Camioneta',
            ],
            [
                'placa' => '8506NXC',
                'marca' => 'Kia',
                'modelo' => 'Sportage',
                'anio'  => 2019,
                'color' => 'Rojo',
                'tipo'  => 'SUV',
            ],
            [
                'placa' => '3729HWP',
                'marca' => 'Hyundai',
                'modelo' => 'Tucson',
                'anio'  => 2021,
                'color' => 'Gris',
                'tipo'  => 'SUV',
            ],
            [
                'placa' => '5841RZD',
                'marca' => 'Toyota',
                'modelo' => 'Yaris',
                'anio'  => 2016,
                'color' => 'Azul',
                'tipo'  => 'Sedán',
            ],
            [
                'placa' => '9263TGM',
                'marca' => 'Ford',
                'modelo' => 'Ranger',
                'anio'  => 2020,
                'color' => 'Blanco',
                'tipo'  => 'Pickup',
            ],
            [
                'placa' => '1738VKL',
                'marca' => 'Suzuki',
                'modelo' => 'Swift',
                'anio'  => 2017,
                'color' => 'Verde',
                'tipo'  => 'Hatchback',
            ],
            [
                'placa' => '6094WBN',
                'marca' => 'Mazda',
                'modelo' => 'CX-5',
                'anio'  => 2023,
                'color' => 'Rojo',
                'tipo'  => 'SUV',
            ],
            [
                'placa' => '2657XQP',
                'marca' => 'Nissan',
                'modelo' => 'Versa',
                'anio'  => 2019,
                'color' => 'Plata',
                'tipo'  => 'Sedán',
            ],
        ]);
    }
}